name: alexkritchevsky
description: A Blog
author: Alex Kritchevsky
markdown: kramdown
timezone: utc
kramdown:
 parse_block_html: true
 input: GFM
 math_engine: mathjax

gems: [jekyll-sitemap]

sass:
 sass_dir: _sass

google_analytics: UA-75007391-1

exclude: [Gemfile,CNAME,README.md]

excerpt_separator: <!--more-->

collections:
  cache:
    output: true