title: alexkritchevsky
description: Math Rants and More
author: Alex Kritchevsky
markdown: kramdown
timezone: utc
highlighter: rouge
kramdown:
 parse_block_html: true
 input: GFM
 math_engine: mathjax
 hard_wrap: true
 syntax_highlighter: rouge

# github pages enforces these, may as well use them locally
lsi: false
safe: true
gist:
  noscript: false

plugins: []

sass:
 sass_dir: css

google_analytics: True

exclude: [Gemfile,CNAME,README.md]

excerpt_separator: <!--more-->

collections:
  notes:
    output: true
  misc:
    output: true
  code:
    output: true